POST http://localhost:3000/api/carros
Content-Type: application/json

{
    "placa": "Saaaa",
    "modelo": "Taaaa",
    "cliente": "aaaa",
    "dataentrada": "2023-11-20",
    "situacao": "aaaa",
    "orgao": "aaa",
    "obs": "aaa",
    "km": "aaa",
    "imagens": ["pomwepwoemfpweofmwe","psodmfpsdomfpsdofmsdpom"]
}
###
GET http://localhost:3000/api/carros

###
GET http://localhost:3000/api/carros/filtrado
Content-Type: application/json

{
    "cliente":"LOCALIZA",
 
}

###
DELETE http://localhost:3000/api/carros
Content-Type: application/json

{
    "id":"655e4d87699f9d08b25f8adb"
}

###
PUT http://localhost:3000/api/carros/65564a23b6f49453f7d4dcec
Content-Type: application/json

{
    "placa": "AAA0A",
    "modelo": "CRETA",
    "cliente": "LOCALIZA",
    "dataentrada": "2023-11-16",
    "situacao": "DESCONHECIDO",
    "orgao": "DESCONHECIDO",
    "obs": "CARRO NOVO",
    "localizacao": "RADAR"
}